version: "3"

services:
  db:
    platform: linux/amd64
    image: percona:5.7.23
    container_name: spichka_website_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build: .
    container_name: spichka_website
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    working_dir: /var/www/html
    volumes:
      - ./themes/spichka:/var/www/html/wp-content/themes/spichka
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      # - ./backup/20240402_spichkamedia_5dc61a8b8eee5d784880_20240402130244_archive.zip:/var/www/html/20240402_spichkamedia_5dc61a8b8eee5d784880_20240402130244_archive.zip
      # - ./backup/installer.php:/var/www/html/installer.php

volumes:
  db_data:
