name: Deploy
run-name: Deploy to ${{ inputs.environment }}

# on:
#   workflow_dispatch:
#     inputs:
#       environment:
#         type: choice
#         description: 'Environment'
#         required: true
#         options:
#           - staging
#           - prod

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./themes/spichka

jobs:
  deploy:
    name: Deploy
    environment: "dev"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Use Node.js 18.x"
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "18.x"
          cache: "yarn"
          cache-dependency-path: ./themes/spichka/yarn.lock

      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile

      # - name: Cache Composer dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/composer-cache
      #     key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install composer dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          working_dir: ./themes/spichka

      - name: Build
        run: yarn build

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SSH_HOST }}
          remote-user: ${{ secrets.SSH_HOST }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          ssh-port: 22
          source-path: ./themes/spichka/
          destination-path: ${{ secrets.SSH_PATH }}
          rsync-options: --dry-run --archive --verbose --compress --delete-after --human-readable --exclude '**/node_modules/**'
