name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./themes/spichka

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Use Node.js 18.x"
        uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "18.x"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn lint
