name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./themes/spichka

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Use Node.js 18.x"
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "18.x"
          cache: "yarn"
          cache-dependency-path: ./themes/spichka/yarn.lock

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint

      - name: Run Blade Formatter
        run: node_modules/.bin/blade-formatter --write resources/**/*.blade.php
