name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./themes/spichka

jobs:
  testing:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: "Получение данных"
        uses: actions/checkout@v4

      - name: "Node.js 18.x"
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "18.x"
          cache: "yarn"
          cache-dependency-path: ./themes/spichka/yarn.lock

      - name: Установка зависимостей
        run: yarn install --frozen-lockfile

      - name: Запуск линтера
        run: yarn lint
